config/routes.rb
Rails.application.routes.draw do
    devise_for :users
  root to: "home#index"
  resources :tasks, except: [:show]
  resources :emails
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :resource_name, :resource, :devise_mapping, :resource_class
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_email, only: [:show, :edit, :update, :destroy]

  # GET /emails
  # GET /emails.json
  def index
    @emails = Email.all
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
    @email.update(read: true) if !@email.read

    respond_to do |format|
      format.html{}
      format.js{}
    end
  end

  # GET /emails/new
  def new
    create
  end

  # GET /emails/1/edit
  def edit
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(body: Faker::Lorem.paragraph, object: Faker::Book.title)

    respond_to do |format|
      if @email.save
        format.html { redirect_to @email, notice: 'Email was successfully created.' }
        format.json { render :show, status: :created, location: @email }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @email.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PATCH/PUT /emails/1
  # PATCH/PUT /emails/1.json
  def update
    if params[:invertRead] == true
      @email.update(read: !@email.read)
      respond_to do |format|
        format.html{}
        format.js{}
      end
    else
      respond_to do |format|
        if @email.update(email_params)
          format.html { redirect_to @email, notice: 'Email was successfully updated.' }
          format.json { render :show, status: :ok, location: @email }
          format.js {}
        else
          format.html { render :edit }
          format.json { render json: @email.errors, status: :unprocessable_entity }
          format.js {}
        end
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @emailId = @email.id;
    @email.destroy
    respond_to do |format|
      format.html { redirect_to emails_url, notice: 'Email was successfully destroyed.' }
      format.json { head :no_content }
      format.js{}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_email
    @email = Email.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def email_params
    params.fetch(:email, {})
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.all
    @categories = Category.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  def new
    @categories = Category.all
  end

  def create
    @task = Task.new(task_params)
    @category = Category.find(category_params)
    @task.category = @category
    if @task.save
      respond_to do |format|
        format.html {
          flash[:notice] = "Task created"
        redirect_to root_path }
        format.js { flash.now[:notice] = "Task created" }
      end
    else
      respond_to do |format|
        format.html {
          flash.now[:notice] = "Please try again"
        redirect_to root_path }
        format.js { flash.now[:notice] = "Please try again"}
      end
    end
  end

  def edit
    @task = Task.find(params[:id])
    @categories = Category.all

  end

  def update
    if params[:origin] == "checkbox" then
      @task = Task.find(params[:id])
      (!params[:task])? (@task.update(status: false)):(@task.update(status: true))
      respond_to do |format|
        format.html {
          flash[:notice] = "Task Status edited"
        redirect_to root_path }
        format.js { flash[:notice] = "Task Status edited"}
      end
    else
      @task = Task.find(params[:id])
      @task.update(task_params)
      respond_to do |format|
        format.html {
          flash[:notice] = "Task edited"
        redirect_to root_path }
        format.js { flash[:notice] = "Task edited"}
      end
    end
  end

  def index
    @tasks = Task.all
  end

  def destroy
    @task = Task.find(params[:id])
    @taskId = @task.id
    @task.destroy
    respond_to do |format|
      format.html {
        flash[:notice] = "Task deleted"
      redirect_to root_path }
      format.js { flash.now[:notice] = "Task deleted" }
    end
  end


  private

  def task_params
    params.permit(:title, :deadline, :description)
  end

  def category_params
    params.require(:Category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h1 class="text-center mb-4">Welcome to my todolist app</h1>
<%= render 'layouts/task_form'  %>
<ul class="nav nav-pills">
  <% @categories.each do  |category|%>
    <li class="btn category-name btn-primary m-1" id="<%= category.id%>"><%= category.title  %></li>
  <%end%>
</ul>
<div class="tab-content">
  <% @categories.each do  |category|%>
    <div id="content-<%= category.id  %>" class="card category-content">
      <h3 class="card-title"><%= category.title  %></h3>
      <ul class= "card-content">
        <% category.tasks.each do |task|  %>
          <li id="task-<%= task.id%>" <% if task.status  %> class="statusTrue" <% end %> >
            <%= task.title  %>
            <% unless task.deadline.nil? %>
              , to read: <%= task.deadline.strftime('%D')  %>
            <%end%>
            <%= check_box_tag :task, task.status, task.status , data: { remote: true, url: task_path(task), params: { id: task.id, origin: "checkbox"}.to_param, method: "put" }%>
            <%= link_to task_path(task), data: {:confirm => 'Are you sure?'}, :method => :delete, remote: true  do %>
              <%= fa_icon "trash-alt", style: "color:orange;"%>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <%end%>
</div>
<div class="container">
  <div class="row d-none">
    <% @tasks.each do |task|  %>
      <div class="card col-3">
        <% unless task.image.nil? %>
          <%= image_tag task.image, class: "carousel-img rounded-circle w-100" %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="carousel m-5">
    <div class="carousel-controller d-flex align-items-center">
      <div class=""><%= fa_icon "arrow-left 2x",  id: "prev", style: "color:grey;"%></div>
      <img class=""src="">
      <div class="" id="next"><%= fa_icon "arrow-right 2x",  id: "next", style: "color:grey;"%></div>
    </div>
    <div class="carousel-indicators">
      <%= fa_icon "grip-lines",class: "indicator m-2 text-danger"%>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_modals.html.erb
<div class="modal-content">
  <div class="modal-header">
    <ul class="nav nav-pills">
      <li class="btn login-tab btn-info m-1">
        <h5 class="modal-title" id="login-tab">Login</h5>
      </li>
      <li class="btn signup-tab btn-info m-1">
        <h5 class="modal-title" id="signup-tab">Signup</h5>
      </li>
    </ul>
    <button id="close-modal" type="button" class="btn btn-danger d-flex-reverse" data-dismiss="modal">Close</button>
  </div>
  <div class="modal-body">
    <div class="tab-content">
      <div id="login-content" class="card category-content text-center">
        <%= render 'devise/sessions/new' %>
      </div>
      <div id="signup-content" class="card category-content d-none text-center">
        <%=render 'devise/registrations/new'%>
        <%= link_to "Forgot your password?", new_password_path(resource_name) , class: "btn btn-info"%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Sandbox App", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% unless user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mail index", emails_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Mail index", emails_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "New task", new_task_path, class: "nav-link" %>
      </li>
    </ul>
    <img class="rounded-circle dropbtn " id="avatar" height="50px" width="50px" src="http://digitalspyuk.cdnds.net/17/25/320x320/square-1498216547-avatar-neytiri.jpg">
    <div class="dropdown-content ml-3">
      <%= link_to "Log in", "#", class: "btn btn-primary", :id => 'login', "data-toggle" => "modal", 'data-target' => '#loginModal' %>
      <%= link_to "Sign up", "#", class: "btn btn-primary", :id => 'signup', "data-toggle" => "modal", 'data-target' => '#loginModal' %>
    </div>
  </div>
</nav>
<!-- Login/signup Modal -->
<div class="modal" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <%= render 'layouts/modals'  %>
</div>

app/views/layouts/_task_form.html.erb
<div class="container">
  <div class="row ml-3">
      <div class="offset-md-3 col-md-6 offset-md-3">
          <%= form_tag(tasks_path, method: "post", class: "form", id: "contact-form")  do %>
              <div class="form-group">
                  <%= label_tag "Task", nil, class: "form-label" %>
                  <%= text_field_tag :title, nil, class: "form-control", placeholder: "Buy burgers" %>
              </div>
              <div class="form-group">
                  <%= label_tag "Deadline", nil, class: "form-label" %>
                  <%= date_field_tag :deadline, nil, class: "form-control" %>
              </div>
              <div class="form-group">
                  <%= label_tag "Category", nil, class: "form-label" %>
                  <%= select_tag "Category", options_from_collection_for_select(@categories, "id", "title", "1"), class: "form-control"  %>
              </div>
              <div class="text-center">
                  <%= submit_tag("Create task", class: "btn btn-start-order") %>
              </div>
          <%end%>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodolistApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--  Font Awesome  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" crossorigin="anonymous">
    <!-- JQUERY -->
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'layouts/navbar'  %>
    <%= render 'layouts/flash'  %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task.html.erb
<li>
  <%= task.title  %>
  <% unless task.deadline.nil? %>
    , to read: <%= task.deadline.strftime('%D')  %>
  <%end%>
</li>

app/views/tasks/_task_list.html.erb
<ul>
  <% @tasks.each do |task|  %>
    <li>
      <%= task.title %>,
      "Deadline : " <%=  task.deadline.strftime("%D")  %>
       <%= link_to "Edit this task", edit_task_path(task) %>
    </li>
  <% end %>
</ul>

app/views/tasks/create.js.erb
$(document).ready(function() {
  $("#content-"+ <%= @task.category_id %>).find("ul").append("<%= j render 'task',task: @task %>");
  $(".category-content").addClass("d-none");
  $('#content-' + <%=@task.category_id %>).removeClass("d-none");
  $(".notice").text("Task sucesfuly added");
});

app/views/tasks/destroy.js.erb
$(document).ready(function() {
  $("#task-"+ <%= @taskId %>).remove();
});

app/views/tasks/edit.html.erb
<h4>Edit your task</h4>
<%= form_tag(task_path, method: "put") do %>
  <div class="form-group">
      <%= label_tag("Your task:") %>
      <%= text_field_tag(:title, @task.title) %>
  </div>

  <div class="form-group">
    <%= label_tag("When is it due for ?") %>
    <%= date_field_tag(:deadline, @task.deadline)  %>
  </div>
    <%= submit_tag("Edit task", class: "btn btn-info") %>
<% end %>
<%= link_to "Delete this task", task_path(@task), method: :delete, class: "btn btn-danger" %>

app/views/tasks/index.html.erb
<% if user_signed_in? %>

  <%= render 'task_list'  %>

<% end %>

<%= link_to "Create a new task", new_task_path, class: "btn btn-info"  %>

app/views/tasks/new.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/task_form'  %>
<% end %>

app/views/tasks/update.js.erb
$(document).ready(function() {
  $("#task-"+ <%= @task.id %>).toggleClass("statusTrue");
  console.log($("#task-"+ <%= @task.id %>));
});